name: yolohome
services:
  mongodb:
    image: mongo:8.0.8-noble
    container_name: mongodb-yolohome
    hostname: mongodb
    restart: always
    ports:
      - '27018:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root