server:
  port: 8080
  servlet:
    context-path: /yolohome

spring:
  application:
    name: yolohome-service
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27018/yolohome?authSource=admin


app:
  adafruit:
    username: quangthanga123
    active_key: aio_Rbjw47d5ZnWgYzqHyK15vP7oXh12

logging:
  level:
    comyourpackage.AdafruitDataScheduler: DEBUG # Thay com.yourpackage bằng package thực tế của bạn
    org.springframework.web.reactive.function.client: TRACE # Để xem chi tiết request/response của WebClient

